### ISSUE TITLE
Auto Environment Detection

### ISSUE THREAD

**Issue by ConnorGraham** [bitovi/bitops#44] opened 2020-12-29 15:27 UTC
Instead of providing the `ENVIRONMENT` env var on every BitOps run, it would be nice if there was an `auto` or `git` mode that would auto-detect what environment to run based on what has changed in the latest commit to the ops repo

**Comment by mickmcgrath13** [comment] 2020-12-30 21:55
related to (duplicate of?) https://github.com/bitovi/bitops/issues/32

**Closed** 2020-12-30 21:58 UTC
Labels: enhancement, triage
